Initial draft of mysql full provisioner
c6o/provisioners pull request #201
Opened 2021-02-03 22:23 UTC by nothingmn

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Unit Tests

Optional:

- [ ] Functional Tests
- [ ] Integration Tests

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2021-02-03 22:41 UTC, nsainaney requested changes

2021-02-03 22:41 UTC, nsainaney commented on packages/mysqld/CHANGELOG.md
> +# Change Log
I'd delete this file - it's autogenerated on publish

2021-02-03 22:41 UTC, nsainaney commented on packages/mysqld/c6o/app.yaml
> +name: Mysql (App)
```suggestion
name: MySql
```

2021-02-03 22:41 UTC, nsainaney commented on packages/mysqld/src/mixins/createValidate.ts
> +        this.spec.secretKeyRef = this.spec.secretKeyRef || 'mongo-connections'
Defaults to mongo-connections

2021-02-03 22:41 UTC, nsainaney commented on packages/mysqld/k8s/statefulset.yaml
> +apiVersion: apps/v1
Should this be a stateful set? How do the MySQL pods discover each other?

2021-02-04 18:00 UTC, nothingmn commented on packages/mysqld/k8s/statefulset.yaml
> +apiVersion: apps/v1
Ill remove the stateful set for now.

2021-02-09 20:21 UTC, closed without merging