bug: Fix build error by adding @c6o/ui-theme to istio dependencies
c6o/provisioners pull request #23
Opened 2020-08-12 18:22 UTC by conneryn

Fix isto build error ( #22) when trying to build from provisioners repository root (ie: not through monorepo).

2020-08-12 22:20 UTC, Canuckaholic requested changes

2020-08-12 22:20 UTC, Canuckaholic commented on yarn.lock
> +    typeface-roboto "^0.0.75"
I just removed roboto from UI Theme. We don't need it.

2020-08-13 01:40 UTC, conneryn commented on yarn.lock
> +    typeface-roboto "^0.0.75"
I think, until a new version of ui-theme is published to NPM, yarn is going to continue to include this as a dependency.

2020-08-13 02:01 UTC, Canuckaholic commented on yarn.lock
> +    typeface-roboto "^0.0.75"
Are you _sure_?

2020-08-13 05:34 UTC, conneryn commented on yarn.lock
> +    typeface-roboto "^0.0.75"
I mean, I'm more or less just taking shots in the dark on everything here.... but I'm pretty sure?

When building the project from `monorepo`, it will use the locally built version of @c6o/ui.  However, when building from this project alone, then @c6o/ui will need to be pulled down from the public NPM repository instead (and thus, it will depend on what was most recently published).

2020-08-18 20:34 UTC, nsainaney reviewed
I think this is already on develop

2020-08-21 17:08 UTC, closed without merging