feat: template for services.
c6o/provisioners pull request #274
Opened 2021-11-03 20:09 UTC by robblovell

## Description

Added a template for the service helper.

2021-11-03 21:17 UTC, nsainaney requested changes

2021-11-03 21:17 UTC, nsainaney commented on packages/common/src/helpers/service.ts
> +import { Namespace, Service } from '@c6o/kubeclient-resources/core/v1'
Namespace not referenced

```suggestion
import { Service } from '@c6o/kubeclient-resources/core/v1'
```

2021-11-04 20:16 UTC, gburnard commented on packages/common/src/helpers/service.ts
> +    static template = (namespace: string, name?: string): Service => ({
```suggestion
    static template = (namespace?: string, name?: string): Service => ({
```

2021-11-04 20:16 UTC, gburnard approved these changes

2021-11-04 20:16 UTC, merged