feat(ingress): Added support for multiple ingress routes, including TCP connections!
c6o/provisioners pull request #46
Opened 2020-08-28 03:02 UTC by gburnard

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2020-08-28 16:42 UTC, nsainaney commented on packages/c6o-system/src/mixins/api/createAppPost.ts
> +        if (app.spec.routes?.length !== 0) {
```suggestion
        if (app.spec.routes?.length) {
```

2020-08-28 19:33 UTC, nsainaney commented on packages/common/src/app.ts
> +    service: string,
```suggestion
    serviceName: string,
```

2020-09-02 21:38 UTC, nsainaney requested changes

2020-09-02 21:38 UTC, nsainaney commented on packages/c6o-system/src/index.ts
> +    routingMixin,
```suggestion
    postAppMixin,
```

2020-09-02 21:38 UTC, nsainaney commented on packages/c6o-system/src/index.ts
> +    routingMixin,
```suggestion
    postAppMixin,
```

2020-09-02 21:38 UTC, nsainaney commented on packages/c6o-system/src/mixins/api/createAppPost.ts
> +export const routingMixin = (base: baseProvisionerType) => class extends base {
```suggestion
export const postAppMixin = (base: baseProvisionerType) => class extends base {
```

2020-09-02 21:38 UTC, nsainaney commented on packages/common/src/app.ts
> +        routes?: Array<RoutesType>
```suggestion
        routes?: RoutesType[]
```

2020-09-02 21:38 UTC, nsainaney commented on packages/c6o-system/src/mixins/api/createAppPost.ts
> +            this.manager.status?.push(`Tearing down app ${app.metadata.namespace} routes`)
```suggestion
            this.manager.status?.push(`Removing App ${app.metadata.namespace} routes`)
```

2020-09-02 21:38 UTC, nsainaney commented on packages/c6o-system/src/mixins/api/createAppPost.ts
>              this.manager.status?.push(`Setting up app ${app.metadata.namespace} routes`)
```suggestion
            this.manager.status?.push(`Creating App ${app.metadata.namespace} routes`)
```

2020-09-02 21:38 UTC, nsainaney commented on packages/c6o-system/src/mixins/api/createAppPost.ts
> +            this.manager.status?.push(`Updating app ${app.metadata.namespace} routes`)
```suggestion
            this.manager.status?.push(`Updating App ${app.metadata.namespace} routes`)
```

2020-09-02 22:03 UTC, gburnard commented on packages/c6o-system/src/mixins/api/createAppPost.ts
> +        if (app.spec.routes?.length !== 0) {
done

2020-09-02 22:03 UTC, gburnard commented on packages/common/src/app.ts
> +    service: string,
done

2020-09-02 22:04 UTC, gburnard commented on packages/c6o-system/src/index.ts
> +    routingMixin,
done

2020-09-02 22:05 UTC, gburnard commented on packages/c6o-system/src/index.ts
> +    routingMixin,
done

2020-09-02 22:05 UTC, gburnard commented on packages/c6o-system/src/mixins/api/createAppPost.ts
> +export const routingMixin = (base: baseProvisionerType) => class extends base {
done

2020-09-02 22:07 UTC, gburnard commented on packages/common/src/app.ts
> +        routes?: Array<RoutesType>
What about marina.menuItems @nsainaney

2020-09-02 22:07 UTC, gburnard commented on packages/c6o-system/src/mixins/api/createAppPost.ts
>              this.manager.status?.push(`Setting up app ${app.metadata.namespace} routes`)
done

2020-09-02 22:08 UTC, gburnard commented on packages/c6o-system/src/mixins/api/createAppPost.ts
> +            this.manager.status?.push(`Updating app ${app.metadata.namespace} routes`)
done

2020-09-02 23:34 UTC, nsainaney approved these changes

2020-09-02 23:34 UTC, merged