feat(drone): Drone provisioner
c6o/provisioners pull request #64
Opened 2020-09-10 21:10 UTC by nothingmn

Fixes #62

2020-09-10 21:28 UTC, nsainaney requested changes

2020-09-10 21:28 UTC, nsainaney commented on packages/drone/CHANGELOG.md
> +# Change Log
Did this file change? Need not be here as its auto generated

2020-09-10 21:28 UTC, nsainaney commented on packages/drone/c6o/manifest.yaml
> +apiVersion: system.codezero.io/v1
I would have expected an app with an array of editions. See the samples folder in czdev (those are JSON but these should be YAML). So technically, this file should be called manifests (plural)

2020-09-10 21:28 UTC, nsainaney commented on packages/drone/k8s/latest/3-server-deployment.yaml
> +        system.codezero.io/edition: latest
Do not add edition here - that'll be set by provisioner

2020-09-10 21:28 UTC, nsainaney commented on packages/drone/k8s/latest/4-runner-deployment.yaml
> +        system.codezero.io/edition: latest
Do not set editions here

2020-09-10 21:28 UTC, nsainaney commented on packages/drone/k8s/latest/5-service.yaml
> +    system.codezero.io/edition: latest
Remove editions

2020-09-10 21:28 UTC, nsainaney commented on packages/drone/package.json
> +  "gitHead": "db2f853696fe6d336812a46d1cac44855aec9dfa"
I've learnt that gitHead need not be checked in

2020-09-10 21:28 UTC, nsainaney commented on packages/drone/src/mixins/createInquire.ts
> +                askAnswered: true,
Should we be asking if this is set in the manifest? Good for debugging

2020-09-10 21:28 UTC, nsainaney commented on packages/drone/src/ui/Main.ts
> +        //our scm provider names are templated based on the dropdown list, just replace the spaces in the name with -
Shouldn't this be checkboxes? Can't user add more than one?

2020-09-10 21:28 UTC, nsainaney commented on packages/drone/src/ui/Main.ts
> +        //our scm provider names are templated based on the dropdown list, just replace the spaces in the name with -
You can pass an array to the mediator if more than one checked

2020-09-10 21:28 UTC, nsainaney commented on packages/drone/src/ui/index.ts
> +export * from './Main'
Arrrg...TitleCase! You win this one Rob....

2020-09-10 21:57 UTC, nothingmn commented on packages/drone/CHANGELOG.md
> +# Change Log
I removed this file.  Was auto-generated and not necessary.

2020-09-10 21:57 UTC, nothingmn commented on packages/drone/c6o/manifest.yaml
> +apiVersion: system.codezero.io/v1
I removed this  file for now.  It needs to be part of a larger conversation.

2020-09-10 22:02 UTC, nothingmn commented on packages/drone/src/ui/Main.ts
> +        //our scm provider names are templated based on the dropdown list, just replace the spaces in the name with -
From what I can tell, you can only set it up against a single SCM.

2020-09-10 22:03 UTC, nothingmn commented on packages/drone/src/ui/index.ts
> +export * from './Main'
Renamed!

2020-09-10 22:10 UTC, nothingmn commented on packages/drone/src/mixins/createInquire.ts
> +                askAnswered: true,
Agreed.  Updated

2020-09-14 22:26 UTC, nsainaney approved these changes

2020-09-14 22:34 UTC, merged